
CREATE TABLE IF NOT EXISTS `tb_jarkom_downtime_daily` (
  `logdown_period` date NOT NULL,
  `id_jarkom` int NOT NULL,
  `kode_jarkom` varchar(45) DEFAULT NULL,
  `id_remote` int DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `kode_provider` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `downtime` int DEFAULT NULL,
  `av` float DEFAULT NULL,
  PRIMARY KEY (`id_jarkom`,`logdown_period`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='tabel hasil perhitungan downtime jarkom per hari';

CREATE TABLE IF NOT EXISTS `tb_remote_copy` (
  `id_remote` int NOT NULL AUTO_INCREMENT,
  `nama_remote` varchar(200) NOT NULL DEFAULT '',
  `kode_uker` varchar(45) DEFAULT NULL,
  `keterangan` text,
  `ip_lan` varchar(45) NOT NULL DEFAULT '',
  `subnet` int DEFAULT NULL,
  `alamat_uker` varchar(200) DEFAULT NULL,
  `telp_uker` varchar(200) DEFAULT NULL,
  `nama_pic` varchar(200) DEFAULT NULL,
  `latitude` varchar(45) NOT NULL DEFAULT '0',
  `longitude` varchar(45) NOT NULL DEFAULT '0',
  `user_creator` varchar(45) DEFAULT NULL,
  `user_update` varchar(45) DEFAULT NULL,
  `create_at` varchar(45) DEFAULT NULL,
  `update_at` varchar(45) DEFAULT NULL,
  `kode_kanca` varchar(45) NOT NULL DEFAULT '',
  `kode_tipe_uker` varchar(45) NOT NULL DEFAULT '',
  `kode_op` int NOT NULL DEFAULT '1',
  `start_nop` varchar(45) DEFAULT NULL,
  `end_nop` varchar(45) DEFAULT NULL,
  `pic_uko` varchar(200) DEFAULT NULL,
  `id_kelurahan` varchar(30) DEFAULT NULL,
  `status_l` int DEFAULT NULL,
  `last_update_l` datetime DEFAULT NULL,
  `status_fail_date_l` datetime DEFAULT NULL,
  `status_rec_date_l` datetime DEFAULT NULL,
  `status_detail_l` varchar(100) DEFAULT NULL,
  `latency_l` float DEFAULT NULL,
  `last_polled_l` datetime DEFAULT NULL,
  `ip_monitoring` varchar(20) DEFAULT NULL,
  `status_alarm` int DEFAULT '0',
  `id_alarm_type` int DEFAULT NULL,
  `notes_alarm` text,
  PRIMARY KEY (`id_remote`,`kode_kanca`,`kode_tipe_uker`),
  UNIQUE KEY `idtb_remote_UNIQUE` (`id_remote`),
  UNIQUE KEY `ip_lan` (`ip_lan`),
  UNIQUE KEY `ip_monitoring` (`ip_monitoring`) USING BTREE,
  KEY `fk_tb_site_tb_kanca1_idx` (`kode_kanca`),
  KEY `fk_tb_site_tb_tipe_uker1_idx` (`kode_tipe_uker`),
  KEY `FK_tb_remote_tb_nop` (`kode_op`),
  KEY `fk_tb_remote_tb_kelurahan` (`id_kelurahan`) USING BTREE,
  KEY `nama_remote` (`nama_remote`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=27863 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `tb_jarkom_copy` (
  `id` int NOT NULL AUTO_INCREMENT,
  `kode_jarkom` varchar(45) NOT NULL DEFAULT '',
  `ip_wan` varchar(45) DEFAULT NULL,
  `id_remote` int NOT NULL DEFAULT '0',
  `brisat` varchar(11) DEFAULT NULL COMMENT '1 = menggunakan brisat, 0 = tidak menggunakan brisat, 2 = Jupiter',
  `bandwidth` varchar(11) DEFAULT NULL,
  `kode_jenis_jarkom` varchar(45) NOT NULL DEFAULT '',
  `kode_provider` varchar(45) NOT NULL DEFAULT '',
  `user_create` varchar(45) DEFAULT NULL,
  `user_update` varchar(45) DEFAULT NULL,
  `create_at` varchar(45) DEFAULT NULL,
  `update_at` varchar(45) DEFAULT NULL,
  `id_spk` int DEFAULT '1',
  `keterangan` text,
  `used_status` varchar(255) DEFAULT '1',
  `status_l` int DEFAULT NULL,
  `last_update_l` datetime DEFAULT NULL,
  `status_fail_date_l` datetime DEFAULT NULL,
  `status_rec_date_l` datetime DEFAULT NULL,
  `latency_l` float DEFAULT NULL,
  `last_polled_l` datetime DEFAULT NULL,
  `status_alarm` int DEFAULT NULL,
  `id_alarm_type` int DEFAULT NULL,
  `notes_alarm` text,
  `brisat_batch` varchar(11) DEFAULT NULL,
  `price` int DEFAULT NULL,
  `id_contract` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `kode_jarkom` (`kode_jarkom`),
  KEY `FK_tb_jarkom_new_tb_jenis_jarkom` (`kode_jenis_jarkom`),
  KEY `id_remote` (`id_remote`),
  KEY `kode_provider` (`kode_provider`) USING BTREE,
  KEY `id_spk` (`id_spk`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=61950 DEFAULT CHARSET=latin1;